# Generated by Django 4.0.4 on 2022-04-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='')),
                ('brand', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('benefits', models.CharField(max_length=60)),
            ],
        ),
    ]
